# Linear Algebra Functions


Numpy is python library which basically provide multidimensional array objects and varoius fuctions which can operate on these array objects. This notebook covers five functions of numpy library which are listed below.
 

- function 1 - np.linalg.eig()
- function 2 - np.linalg.det()
- function 3 - np.linalg.inv()
- function 4 - np.linalg.matrix_power()
- function 5 - np.linalg.solve()

This notebook will also cover one case each at which the function blows-up or in which you need to take some extra care while using these functions.

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [65]:
# List of functions explained 
function1 = 'np.linalg.eig()'
function2 = 'np.linalg.det()'
function3 = 'np.linalg.inv()'
function4 = 'np.linalg.matrix_power()'
function5 = 'np.linalg.solve()'

## Function 1 - np.linalg.eig()

This function takes a square matrix as input and returns an array of eigen values and a matrix of which i column represents the eigen vector corrseponding to i eigenvalue in that array.  

In [31]:
# Example 1 - working
arr1 = [[1, 0], 
        [0, 1]]
x, y = np.linalg.eig(arr1)
print(x)
print(y)

<class 'list'>
[1. 1.]
[[1. 0.]
 [0. 1.]]


In [23]:
# Example 2 - working
arr2 = [[0, 1, 3, 0],
        [-2, 3, 0, 4],
        [0, 0, 6, 1],
        [0, 0, 1, 6]]
a, b = np.linalg.eig(arr2)
print(a)
print(b)

[1. 2. 7. 5.]
[[-0.70710678 -0.4472136   0.31747032 -0.06428243]
 [-0.70710678 -0.89442719  0.43652168  0.83567165]
 [ 0.          0.          0.59525684 -0.38569461]
 [ 0.          0.          0.59525684  0.38569461]]


Explanation about example

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = [[1, 2, 5], 
        [3, 4., 7]]
c, d = np.linalg.eig(arr3)

LinAlgError: Last 2 dimensions of the array must be square

Because eigenvectors exists for only square matrices, and because this is isn't square matrix it gives "LinAlgerror"  

While using this function always keep the round off error in mind

## Function 2 - np.linalg.det()

This function returns the value of determinant of matrix which is passed as an argument in it

In [32]:
# Example 1 - working
arr4 = [[1, 4],
        [6, 7]]
det4 = np.linalg.det(arr4)
det4

-17.0

In [33]:
# Example 2 - working
arr5 = [[0, 1, 3, 0],
        [-2, 3, 0, 4],
        [0, 0, 6, 1],
        [0, 0, 1, 6]]
det5 = np.linalg.det(arr5)
det5

69.99999999999996

In this example you can see that the function returns 69.999999996 instead of 70(which is actual determinant value). So while using this function keep the Round Off Error in your mind.   

In [34]:
# Example 3 - breaking (to illustrate when it breaks)
arr6 = [[1, 2, 3],
        [4, 5, 6]]
det6 = np.linalg.det(arr6)

LinAlgError: Last 2 dimensions of the array must be square

This happens because arr6 is not a square matrix.

## Function 3 - np.linalg.inv()

This function returns a matrix which is the multiplicative matrix of the matrix which was passed as an argument.
This means that if A is a square matrix than.
   np.linalg.inv(A) @ A = I        
(where I is the identity matrix of same order that of A)

In [41]:
# Example 1 - working
arr7 = [[1, 2, 3],
        [4, 5, 6],
        [7, 2, 9]]
inv7 = np.linalg.inv(arr7)
inv7

array([[-0.91666667,  0.33333333,  0.08333333],
       [-0.16666667,  0.33333333, -0.16666667],
       [ 0.75      , -0.33333333,  0.08333333]])

Explanation about example

In [42]:
# Example 2 - working
arr8 = [[1, 5],
        [7, 8]]
inv8 = np.linalg.inv(arr8)
inv8

array([[-0.2962963 ,  0.18518519],
       [ 0.25925926, -0.03703704]])

Explanation about example

In [46]:
# Example 3 - breaking (to illustrate when it breaks)
arr9 = [[3, 5, 9],
        [1, 2, 4],
        [2, 3, 5]]
inv9 = np.linalg.inv(arr9)
inv9

array([[ 1.50119988e+15, -1.50119988e+15, -1.50119988e+15],
       [-2.25179981e+15,  2.25179981e+15,  2.25179981e+15],
       [ 7.50599938e+14, -7.50599938e+14, -7.50599938e+14]])

You must be wondering that why this code is not giving error(because the matrix arr9 is non invertible). This is happening becuse of round off error, according to compiler this matrix doesn't have zero determinat instead a value which is very very small. 
So this an error which doesn't give error. 

Some closing comments about when to use this function.

## Function 4 - np.linalg.matrix_power()

This function basically does the matrix multiplication multiple times. Means if you want the result of a matrix raised to some power than this function is best apply.

In [48]:
# Example 1 - working
arr10 = [[1, 2],
         [2, 1]]
cube_of_arr10 = np.linalg.matrix_power(arr10, 3)
cube_of_arr10

array([[13, 14],
       [14, 13]])

In [49]:
# Example 2 - working
arr11 = [[1, 5],
         [7, 8]]
inverse_of_arr11 = np.linalg.matrix_power(arr11, -1)
inverse_of_arr11

array([[-0.2962963 ,  0.18518519],
       [ 0.25925926, -0.03703704]])

This function can also be used to calculate inverse of a matrix

In [50]:
# Example 3 - breaking (to illustrate when it breaks)
arr12 = [[1, 5],
         [2, 6],
         [1, 4]]
mul_of_arr12 = np.linalg.matrix_power(arr12, 3)

LinAlgError: Last 2 dimensions of the array must be square

Beacuse only a square matrix can be multiplied to itself, other matrices would give an error

## Function 5 - np.linalg.solve()

This function solves the linear equations. It the takes input a matrix and a array and then solves the equation AX = B and than returns an array X

In [57]:
# Example 1 - working
arr13 = [[1, 2],
         [3, 4]]
b13 = [5, 10]
sol13 = np.linalg.solve(arr13, b13)
sol13

array([0. , 2.5])

In [60]:
# Example 2 - working
arr14 = [[1, 2, 3],
         [4, 5, 6],
         [1, 0, 1]]
b14 = [5, 6, 7]
sol14 = np.linalg.solve(arr14, b14)
sol14

array([ 1.33333333, -6.66666667,  5.66666667])

Explanation about example

In [61]:
# Example 3 - breaking (to illustrate when it breaks)
arr15 = [[1, 2],
         [2, 4]]
b15 = [6, 7]
sol15 = np.linalg.solve(arr15, b15)

LinAlgError: Singular matrix

This happenes because the matrix which you given as input is a singular matrix that's why either this system of linear equation will have infinite silutions or no solutions.

## Conclusion

So this was a brief explanation of five functions of numpy library specifically focused on linear algebra functions.
In this notebook you learnt about 
1. Finding eigen values and eigen vectors using np.linalg.eig()
2. Finding determinat of a matrix using using np.linalg.det()
3. Finding inverse of a matrix using using np.linalg.inv()
4. Exponentiation of a matreix using np.linalg.matrix_power()
5. Solving a system of linear equations using np.linalg.solve()

Using numpy library you can perform many more such things. If you want to explore it more you can go through the below links. 

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numoy official documentation : https://numpy.org/doc/stable/reference/routines.html